### PR TITLE
Update types

### PR DESCRIPTION
**Pull request by bkiac**

### CODE REVIEW

**Comment by bkiac** [comment]
@alexbosworth I'm not sure why CI is failing, I haven't changed any JS code and this is the output of the test suite:

```
# tests 1989
# suites 0
# pass 1989
# fail 0
# cancelled 0
# skipped 0
# todo 0
# duration_ms 307605.365143
```

seems like all the tests are passing so I don't know why the process exits with code 1, can you take a look?

**Comment by alexbosworth** [comment]
hmm looks like the test coverage part messes up the CI for some reason

**Comment by alexbosworth** [comment]
i'll look into how to fix it or if I can't figure it out I'll remove the nyc part

**Comment by alexbosworth** [comment]
ok i modified the CI, maybe it will work now? Also I changed openChannel to accept UTXOs, it takes an optional array `inputs` with the attributes `transaction_id` a hex tx id and `transaction_vout` a numeric output index

**Comment by bkiac** [comment]
checks are passing now, and I updated the types of `openChannel` too

**Review by alexbosworth — APPROVED** [review]

**Pull request merged**
