### PR TITLE
Move type definitions next to their source

### PR DESCRIPTION
**Pull request by bkiac**

### CODE REVIEW

**Comment by alexbosworth** [comment]
Is this strictly required? What if the typescript supporting methods were just exposed at the top level and you only import them from there?

**Comment by bkiac** [comment]
> What if you do import {authenticatedLndGrpc} from "lightning" does that work?

That does work, yes.

> Is this strictly required? What if the typescript supporting methods were just exposed at the top level and you only import them from there?

It's not required, but in my opinion, it's good practice to have the typescript definitions next to the js modules, otherwise, submodules don't have typescript declaration files. Importing from any submodule (like `import {authenticatedLndGrpc} from "lightning/lnd_grpc"`) is technically correct even though docs advise to import from top-level `lightning`.

If you only want to officially support importing from top level and you don't want to pollute the js code with .d.ts files we could go with exposing typescript methods at the top level.

**Comment by alexbosworth** [comment]
Yeah I want to avoid supporting deep requires

Instead I would go for what you propose, but by abstracting out the dirs into dedicated repos

I'll try and do a new release with the updated typescript that is in master now, I just need to do some final tests. There are also more methods coming over from ln-service

**Comment by bkiac** [comment]
Should I continue adding types using this pattern in the following PRs? I used this #11 because none of the remaining untyped methods are exported from index.js.

**Comment by alexbosworth** [comment]
> Should I continue adding types using this pattern in the following PRs? I used this #11 because none of the remaining untyped methods are exported from index.js.

Yes, if you add types to a method, please add it to index.js

**Comment by bkiac** [comment]
Okay, should I add them to the README also?

Is there something you would like to have in this PR before it can be merged?

**Comment by alexbosworth** [comment]
Sure add them to the README if you want

**Comment by alexbosworth** [comment]
If you add them, it might be good to do them in small PRs to make things easier, I'm still working on bringing more methods over and increasing unit test coverage but making progress on that

**Comment by bkiac** [comment]
Sure, will do. I will try to add them more consistently in the following weeks.

**Pull request merged**
