### PR TITLE
Add types

### PR DESCRIPTION
**Pull request by bkiac**
Extends https://github.com/alexbosworth/lightning/pull/8

Failing tests and issues with missing modules from the bundle are fixed.
Typescript files are replaced by type declarations for the JS functions.

I will leave this as WIP until I add some tests for the types.

### CODE REVIEW

**Comment by bkiac** [comment]
I think it should be good now

**Comment by alexbosworth** [comment]
Great, are there next steps?

**Comment by bkiac** [comment]
Sure, now we have a good system to build on, I will continue adding types when I find the time

**Comment by alexbosworth** [comment]
Sounds good, I'll try to continue to move over the methods from ln-service so they are all present in this repo and have more complete unit test coverage

**Pull request merged**
