### PR TITLE
Add types for lnd_methods/offchain methods

### PR DESCRIPTION
**Pull request by bkiac**
I started working on the offchain methods and I have a few questions:
- `attemptRoute` and `emitPayment` are not exported from the offchain module. Are these methods only to be used inside the library or are they mistakenly unexported?
- Few of the `confirmedFromPayment` method's argument type descriptions are different than the types used in the tests:
Here, `chan_capacity`, `fee` and `fee_msat` are numbers
https://github.com/alexbosworth/lightning/blob/a25e4fd8d6286a9ae3235f840d6ad225649c5850/lnd_responses/confirmed_from_payment.js#L66-L75
but in the related test, they are passed as strings:
https://github.com/alexbosworth/lightning/blob/a25e4fd8d6286a9ae3235f840d6ad225649c5850/test/lnd_responses/test_confirmed_from_payment.js#L18-L30
Which are the correct types?

### CODE REVIEW

**Comment by alexbosworth** [comment]
`attemptRoute` and `emitPayment` are internal yes, as is `confirmedFromPayment`

You're right `chan_capacity`, `fee` and `fee_msat` are String types the doc should be adjusted

**Comment by alexbosworth** [comment]
You can see the methods that should be exported at the top level because they are already exported in `lnd_methods`

**Comment by bkiac** [comment]
The tests use `custom_records` object that is not mentioned in the arguments description, is this an optional value?
https://github.com/alexbosworth/lightning/blob/a25e4fd8d6286a9ae3235f840d6ad225649c5850/test/lnd_responses/test_confirmed_from_payment.js#L23

**Comment by alexbosworth** [comment]
> The tests use `custom_records` object that is not mentioned in the arguments description, is this an optional value?
> https://github.com/alexbosworth/lightning/blob/a25e4fd8d6286a9ae3235f840d6ad225649c5850/test/lnd_responses/test_confirmed_from_payment.js#L23

it's an oversight in the doc there, I can fix that

**Comment by bkiac** [comment]
I found another difference between the docs and the test case:
the test uses `fee` arg but it's missing from the docs:
https://github.com/alexbosworth/lightning/blob/a25e4fd8d6286a9ae3235f840d6ad225649c5850/lnd_responses/confirmed_from_payment.js#L19-L20
https://github.com/alexbosworth/lightning/blob/a25e4fd8d6286a9ae3235f840d6ad225649c5850/test/lnd_responses/test_confirmed_from_payment.js#L10-L12

**Comment by bkiac** [comment]
> You can see the methods that should be exported at the top level because they are already exported in `lnd_methods`

Are all of the methods in `lnd_responses` internal? They are exported from `lnd_responses/index.js` but you had mentioned that `confirmedFromPayment` is an internal method.

**Comment by alexbosworth** [comment]
> > You can see the methods that should be exported at the top level because they are already exported in `lnd_methods`
> 
> Are all of the methods in `lnd_responses` internal? They are exported from `lnd_responses/index.js` but you had mentioned that `confirmedFromPayment` is an internal method.

Yeah those also should not be exported

**Comment by alexbosworth** [comment]
> I found another difference between the docs and the test case:
> the test uses `fee` arg but it's missing from the docs:
> https://github.com/alexbosworth/lightning/blob/a25e4fd8d6286a9ae3235f840d6ad225649c5850/lnd_responses/confirmed_from_payment.js#L19-L20
> 
> 
> https://github.com/alexbosworth/lightning/blob/a25e4fd8d6286a9ae3235f840d6ad225649c5850/test/lnd_responses/test_confirmed_from_payment.js#L10-L12

In this case I think the test is wrong

**Comment by alexbosworth** [comment]
I think in the future the LND responses and request mapping functions could be abstracted out to a separate library and then exporting them would make more sense but in this library the goal is that you would not have to ever deal with the standard LND API responses, they'd always be mapped into more JS friendly versions so you wouldn't need the response parsing as a caller

**Comment by bkiac** [comment]
The `offchain` types should be done now.
I think one of the args had the wrong type so I took the liberty to change the docs in this commit: https://github.com/alexbosworth/lightning/pull/22/commits/461f675e36fe3fac736726a40dec06d82fbf008c

**Review by alexbosworth — APPROVED** [review]

**Pull request merged**
