### PR TITLE
Add types

### PR DESCRIPTION
**Pull request by bkiac**
I started working on the types as we talked about in https://github.com/alexbosworth/ln-service/pull/135.

I only changed the types of existing modules in the typescript directory for now. I have a few notes about how to continue the process:
- I removed the args and return type information from the JSDoc because I felt they aren't necessary for TypeScript, but it might be beneficial to have them copied over to the built JS, so I can put them back if you like.
- I replaced the default exports with named exports so the reexporting of the functions and types is easier in the index files.
- I think it would be better if the source code and build output are separated, so the typescript directory is cleaner. It will get messy if all of the type source code, built JS, source maps and declarations are in that folder.

I've also added two more functions for `lndGateway` to provide improved type safety: `authenticatedLndGateway` and `unauthenticatedLndGateway` which return `AuthenticatedLnd` and `UnauthenticatedLnd` respectively while the `lndGateway` returns the union of these two. I added these because I could not make the `lndGateway` work with conditional return type based on the `macaroon` argument.

I will start moving over the `lightning` related methods from https://github.com/alexbosworth/ln-service/pull/135 if you feel like the current changes of this PR is adequate.

### CODE REVIEW

**Comment by alexbosworth** [comment]
Sure this seems cool to me

I don't really use typescript myself so hard to judge but since it can pass through a layer of typing I think this should work great

What is required to move from WIP to ready?

**Comment by bkiac** [comment]
I would like to keep it WIP until I move all of the `lightning` related types here from https://github.com/alexbosworth/ln-service/pull/135.

**Comment by alexbosworth** [comment]
OK, there are still a bunch over there though it might be easier to do things piecemeal

**Comment by bkiac** [comment]
Yeah, it might be better to open incremental PRs.
I updated the compilation config and scripts, if you think it's ok, the changes can be merged.

**Comment by alexbosworth** [comment]
I'm ok to merge it in but it looks like there is a conflict still

**Comment by bkiac** [comment]
Yep, sorry about that. Should be good now.

**Comment by alexbosworth** [comment]
It's failing some tests actually

**Comment by bkiac** [comment]
It might be because some of the tests relied on importing from the compiled index.js, I will try to fix them today

**Comment by alexbosworth** [comment]
I also see the error when requiring the index.js outside of the project as well, somehow it can't find some imports that it needs

**Comment by bkiac** [comment]
oh, that must be because `tsc` only includes the typescript files and their compiled JS in the bundle, I'm guessing the missing imports have no types yet
I will try to fix these in a PR soon

**Comment by bkiac** [comment]
I fixed the failing tests, but I'm not sure how to proceed with the missing modules.

The problem is that I specified in the package.json that only the `dist` directory should be included in the npm bundle. Without the `files` property in the package.json, both the source code and the compiled output have been included so the imports worked.

I tried to set the `allowJs` key in tsconfig.json to include JS files in the compiled output, but TypeScript can't reliably infer the return types of some of the functions therefore `tsc --build` will fail.

Example:
image

I think it would be enough to create only type declaration files instead of reexporting the JS modules through a TypeScript function if you only want TypeScript support for the consumer. This would make the `tsc` script obsolete, so if you would like to support some specific, older versions of Node.js a different bundler would do the trick, otherwise the repository can be published as an npm package as is.

**Comment by alexbosworth** [comment]
How old are the versions of node.js that won't work?

**Comment by alexbosworth** [comment]
I don't use typescript myself so it makes it a bit difficult to check on what is the right way to go, but as long as it works with regular node.js somehow or with some documented way then I think that can work

**Comment by bkiac** [comment]
> How old are the versions of node.js that won't work?

The current target in tsconfig.json is `es2017` so if you would use newer features they would be transpiled to be compatible with ES2017 spec. I don't think any feature is used right now that would be incompatible with the specified Node.js version of `>=10.10.0` so this is not an issue, but I meant that if you were to use newer ecmascript features or support an older Node.js engine, a different bundler than `tsc` might be a better choice since you don't use TypeScript in the source code.

The source code is in JS, so I think it would be easier to stick to type declaration files and remove the `tsc` dependency, this way the consumer can have type information without `tsc` causing hiccups in tests or in the published npm package.

**Comment by alexbosworth** [comment]
Sure that sounds ok to me

**Comment by alexbosworth** [comment]
The one thing I would want is some way to test that the types are good

**Pull request merged**
