### PR TITLE
Add lnd methods onchain types

### PR DESCRIPTION
**Pull request by bkiac**

### CODE REVIEW

**Comment by alexbosworth** [comment]
@nicolasburtey I think you were looking for some of these types right?

**Comment by nicolasburtey** [comment]
indeed! planned on working on them next week. thanks @bkiac for doing this work!

**Comment by bkiac** [comment]
it's mostly done now, the `closeChannel` args type is incomplete
I'm trying to handle the differences between cooperative and force close arguments so not all of the keys are optional but it's tricky

**Comment by bkiac** [comment]
I have a few questions about the behavior of `closeChannel` because I made a few assumptions, guesses about it to create the types, please correct if any of them are incorrect:

Channel identification:
- At least one of the `id`, `transaction_id` and `transaction_vout` is required and `transaction_id` and `transaction_vout` are not allowed together
Is passing `id` together with `transaction_id` or `transaction_vout` valid because one of them will take precedence over the other? Should users usually just pass one of the three properties?

Force close:
- If `is_force_close` is true `address` and `tokens_per_vbyte` must be undefined, but the rest of the args (`public_key`, `socket`, `target_confirmations`) are also discarded / unused
Is any of the discarded keys relevant or necessary when force closing?

Cooperative close:
- Channels are closed cooperatively by default
- Closing cooperatively requires both `public_key` and `socket`
I'm confused about these two because the documentation mentions that "If cooperatively closing, pass a public key and socket to connect" but the example uses this snippet: `const closing = await closeChannel({id, lnd});` which might be incorrect or I'm missing something. Are `public_key` and `socket` generally optional properties and only required together when one of them is set?
- Only one of `target_confirmations` and `tokens_per_vbyte` can be set or both of them are undefined
Should it be required to pass one of these two or is it fine if both are undefined?

**Comment by alexbosworth** [comment]
> At least one of the id, transaction_id and transaction_vout is required and transaction_id and transaction_vout are not allowed together

Either pass channel id, or transaction id and transaction vout, not both

> If is_force_close is true address and tokens_per_vbyte must be undefined, but the rest of the args (public_key, socket, target_confirmations) are also discarded / unused
Is any of the discarded keys relevant or necessary when force closing?

Socket/public key, target confs are not necessary when force closing no.

Maybe target confs should be required to be undefined on force close too

> Channels are closed cooperatively by default
> Closing cooperatively requires both public_key and socket

No, specifying public key requires also specifying socket. Public key is optional for cooperative close

Specifying the public key and socket will try to connect to the peer before starting the cooperative close attempt

> Only one of target_confirmations and tokens_per_vbyte can be set or both of them are undefined
> Should it be required to pass one of these two or is it fine if both are undefined?

Only one should be defined since they could conflict with each other

**Comment by bkiac** [comment]
Thanks, I think I handled everything, but check the `closeChannel` tests to make sure please

`public_key` and `socket` are disallowed now when `is_force_close: true` because the `addPeer` method exits early without adding a peer when force closing and the types were easier this way, is this okay?

**Pull request merged**
